### ISSUE TITLE
Invsys idle

### ISSUE THREAD

**Issue by Exceptionflug** [MrCreeperkopf/OpenWSK#1]
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_74]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_74]
        at net.thecobix.openwsk.invitation.InvitationSystem$1.run(InvitationSystem.java:28) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]

**Comment by Exceptionflug** [comment]
Solved.
